// <auto-generated />
using Departmanlar.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Departmanlar.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Departmanlar.Models.departmanlar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("departmanAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("departmanlars");
                });

            modelBuilder.Entity("Departmanlar.Models.personel", b =>
                {
                    b.Property<int>("perId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("perId"));

                    b.Property<int>("departmanlarID")
                        .HasColumnType("int");

                    b.Property<string>("perAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("perSehir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("perSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("perId");

                    b.HasIndex("departmanlarID");

                    b.ToTable("personels");
                });

            modelBuilder.Entity("Departmanlar.Models.personel", b =>
                {
                    b.HasOne("Departmanlar.Models.departmanlar", "departmanlar")
                        .WithMany("personel")
                        .HasForeignKey("departmanlarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("departmanlar");
                });

            modelBuilder.Entity("Departmanlar.Models.departmanlar", b =>
                {
                    b.Navigation("personel");
                });
#pragma warning restore 612, 618
        }
    }
}
